spring:
  application:
    name: kafka-demo
  kafka:
    template:
      default-topic: kafka-demo-topic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092

server:
  port: 8081
